"""Add used_lesson_count to Booking model

Revision ID: 154f343f3dcf
Revises: b62287c4c30e
Create Date: 2025-05-06 19:08:22.331871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154f343f3dcf'
down_revision = 'b62287c4c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_lesson_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('used_lesson_count')

    # ### end Alembic commands ###
