"""Add Pro, Booth models and update User model fields

Revision ID: 49bcb34be70d
Revises: 
Create Date: 2025-05-05 19:02:21.511919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bcb34be70d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('system_type', sa.Enum('QED', 'KAKAO', name='boothsystemtype'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('current_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'BOOKED', 'OFFLINE', 'MAINTENANCE', name='boothstatus'), nullable=True),
    sa.Column('last_status_update', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('master_expiry_date', sa.Date(), nullable=True),
    sa.Column('remaining_lesson_total', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))

    op.drop_table('user')
    op.drop_table('pro')
    op.drop_table('booth')
    # ### end Alembic commands ###
