"""Add TicketTemplate, Ticket, Holding models

Revision ID: b23cda2bfc28
Revises: 2cc549afaca5
Create Date: 2025-05-06 15:35:10.669335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cda2bfc28'
down_revision = '2cc549afaca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PERIOD', 'COUNT', 'COUPON', 'LESSON_ADD', 'COMBO', name='ticketcategory'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('total_lesson_count', sa.Integer(), nullable=True),
    sa.Column('default_validity_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('total_taseok_count', sa.Integer(), nullable=True),
    sa.Column('remaining_taseok_count', sa.Integer(), nullable=True),
    sa.Column('total_lesson_count', sa.Integer(), nullable=True),
    sa.Column('remaining_lesson_count', sa.Integer(), nullable=True),
    sa.Column('pro_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_used_up', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['pro.id'], ),
    sa.ForeignKeyConstraint(['ticket_template_id'], ['ticket_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_ticket_template_id'), ['ticket_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_user_id'), ['user_id'], unique=False)

    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_ticket_id'))

    op.drop_table('holding')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_user_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_template_id'))

    op.drop_table('ticket')
    op.drop_table('ticket_template')
    # ### end Alembic commands ###
