"""Add Booking model and related enums

Revision ID: b62287c4c30e
Revises: b23cda2bfc28
Create Date: 2025-05-06 18:19:36.255964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62287c4c30e'
down_revision = 'b23cda2bfc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=True),
    sa.Column('booking_type', sa.Enum('TASEOK_ONLY', 'LESSON', name='bookingtype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED_USER', 'CANCELLED_ADMIN', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('used_taseok_ticket_id', sa.Integer(), nullable=True),
    sa.Column('used_lesson_ticket_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booth_id'], ['booth.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pro.id'], ),
    sa.ForeignKeyConstraint(['used_lesson_ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['used_taseok_ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booth_id'), ['booth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_pro_id'), ['pro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_start_time'))
        batch_op.drop_index(batch_op.f('ix_booking_pro_id'))
        batch_op.drop_index(batch_op.f('ix_booking_booth_id'))

    op.drop_table('booking')
    # ### end Alembic commands ###
